---
version: 2.1

jobs:
  build:
    environment:
      REGISTRY: quay.io
      AUTHOR: appvia
      IMAGE: kore-example
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building Image
          command: |
            VERSION=${CIRCLE_TAG:-latest} make

  publish:
    environment:
      REGISTRY: quay.io
      AUTHOR: appvia
      IMAGE: kore-example
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Publishing Images to registry
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${REGISTRY}
            VERSION=${CIRCLE_TAG:-latest} make
            VERSION=${CIRCLE_TAG:-latest} make release

  deploy:
    environment:
      CLUSTER: rohith
      KORE_TEAM: rohith-qa
    docker:
      - image: quay.io/appvia/kore:rohith
    steps:
      - checkout
      - run:
          name: Configuration Kubeconfig
          command: |
            kore kubeconfig --cluster ${CLUSTER} --non-interactive
      - run:
          name: Deploying application
          command: |
            kubectl --context ${KORE_TEAM}.${CLUSTER} apply -f kube/deployment.yml

workflows:
  version: 2.1
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*$/
      - publish:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*$/
      - deploy:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*$/
          requires:
            - publish
